.\" hosted-engine - Tool for handling hosted engine
.TH "HOSTED-ENGINE" "8" "2013-09-06" "oVirt" "oVirt Hosted Engine Setup Manual"
.SH "NAME"
hosted\-engine \- Tools for handling hosted engine
.SH "SYNOPSIS"
\fBhosted\-engine\fP [options]
.PP
.SH "DESCRIPTION"
.PP
The \fBhosted\-engine\fP command deploys a virtual machine that you can
install oVirt Open Virtualization Manager on to.
The Manager installation on your hosted-engine virtual machine can manage
the host it is running on.
The hosted-engine command can also be used to start, stop and access the
hosted-engine virtual machine.
\&

.SH "OPTIONS"
The following are general options you can use with this command:\&
.IP "\fB\-\-help\fP"
Show the help message and exit.\&
.IP "\fB\-\-deploy\fP"
Run the ovirt-hosted-engine-setup command to deploy the hosted-engine virtual
machine.\&
.IP "\fB\-\-vm-start\fP"
Start VM on this host.\&
.IP "\fB\-\-vm-shutdown\fP"
Gracefully shutdown the VM on this host.\&
.IP "\fB\-\-vm-poweroff\fP"
Forcefully poweroff the VM on this host.\&
.IP "\fB\-\-vm-status\fP"
Show the VM status.\&
.IP "\fB\-\-add-console-password=<password>\fP"
Create a temporary password for VNC/SPICE connections to the hosted-engine
virtual machine.\&
.IP "\fB\-\-console\fP"
Open the configured console using remote-viewer on localhost.\&
.IP "\fB\-\-check-liveliness\fP"
Checks liveliness page of engine.\&
.IP "\fB\-\-connect-storage\fP"
Manually connect the storage domain to the local VDSM instance.\&
.IP "\fB\-\-start-pool\fP"
Start the storage pool manually.\&

.SH "SEE ALSO"
.BR ovirt\-hosted\-engine\-setup (8)
