.\" ovirt-hosted-engine-setup - Tool for deploying hosted engine VM
.TH "ovirt-hosted-engine-setup" "8" "" "Sandro Bonazzola" ""
.SH "NAME"
ovirt\-hosted\-engine\-setup \- Tool for deploying hosted engine VM
.SH "SYNOPSIS"
\fBovirt\-hosted\-engine\-setup\fP [options]
.PP
.SH "DESCRIPTION"
.PP
The \fBovirt\-hosted\-engine\-setup\fP command can be used for deploying a VM
that will host an Enterprise Virtualization Manager that will be able to
manage the same host running the VM.
\&

.SH "GENERAL OPTIONS"
The following are general options you can use with this command:\&
.IP "\fB\-\-help\fP"
Show the help message and exit.\&
.IP "\fB\-\-config-append=file\fP"
Load extra configuration files.\&
.IP "\fB\-\-generate-answer=file\fP"
Generate answer file.\&

.SH "SEE ALSO"
.BR hosted\-engine (8)

.SH "AUTHORS"
.nf
Alex Lourie\&
Sandro Bonazzola\&
Yedidyah Bar David\&
