.\" ovirt-hosted-engine-cleanup - Tool for deconfigure hosted engine
.TH "OVIRT-HOSTED-ENGINE-CLEANUP" "8" "2017-07-17" "oVirt" "oVirt Hosted Engine Cleanup Manual"
.SH "NAME"
ovirt\-hosted\-engine\-cleanup \- Tool for deconfigure hosted engine
.SH "SYNOPSIS"
\fBovirt\-hosted\-engine\-cleanup\fP [options]
.PP
.SH "DESCRIPTION"
.PP
The \fBovirt\-hosted\-engine\-cleanup\fP command de-configure the host
to run ovirt-hosted-engine-setup from scratch.
\&

.SH "OPTIONS"
The following are general options you can use with this command:\&
.IP "\fB\-\-h\fP"
Show the help message and exit.\&
.IP "\fB\-\-q\fP"
Quiet mode, do not prompt for confirmation. Dangerous!!!
\&
