---
name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-8
            shortcut: cs8
            container-name: el8stream
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream
    name: ${{ matrix.name }}
    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}
    steps:
      - uses: actions/checkout@v2

      # Requried for python3-isort on cs8
      - name: Prepare CentOS Stream 8 environment
        if: ${{ matrix.shortcut == 'cs8' }}
        run: |
          dnf copr enable -y sbonazzo/EL8_collection

      # Requried for python3-isort on cs9
      - name: Prepare CentOS Stream 9 environment
        if: ${{ matrix.shortcut == 'cs9' }}
        run: |
          dnf copr enable -y sbonazzo/EL9Collection

      - name: Install testing dependencies
        run: |
          dnf install -y --setopt=tsflags=nodocs \
            python3-isort \
            python3-pycodestyle \
            python3-pyflakes

      # TODO: Split to separate steps?
      - run: automation/check-patch.sh

      - name: Upload artifacts
        uses: ovirt/upload-rpms-action@v2
        with:
          directory: exported-artifacts
