---
name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream
          - name: centos-stream-10
            shortcut: cs10
            container-name: el10stream
    name: ${{ matrix.name }}
    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}
    steps:
      - uses: actions/checkout@v5

      - name: Install testing dependencies
        run: |
          pip3 install isort pycodestyle pyflakes

      - name: Mark git repo as safe
        run: git config --global --add safe.directory $(pwd)

      - name: Install build dependencies
        run: dnf install -y gettext-devel python3-pytest

      - name: Run automation/check-patch.sh
        run: automation/check-patch.sh

      - name: Upload artifacts
        uses: ovirt/upload-rpms-action@main
        with:
          directory: exported-artifacts
