name: Check patch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-el8:

    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8

    steps:
    - name: Import ovirt-master-snapshot key
      run: rpm --import https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/pubkey.gpg

    - run: rpm --import https://copr-be.cloud.fedoraproject.org/results/sbonazzo/EL8_collection/pubkey.gpg

    - name: Install ovirt-release-master
      run: dnf --repofrompath=ovirt-master-snapshot,https://download.copr.fedorainfracloud.org/results/ovirt/ovirt-master-snapshot/centos-stream-8-x86_64/ install -y ovirt-release-master

    - name: Install dependencies
      run: dnf install -y --setopt=tsflags=nodocs --repofrompath epel8,https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/ --repofrompath el8collection,https://copr-be.cloud.fedoraproject.org/results/sbonazzo/EL8_collection/epel-8-x86_64/ ansible-lint autoconf automake createrepo_c dnf dnf-plugins-core dnf-plugin-versionlock dnf-utils gettext-devel git make python3-coverage python3-isort python3-pycodestyle python3-pyflakes rpm-build gettext python3-devel gcc

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: automation/check-patch.sh
      # TODO: Split to separate steps?

    - name: archive artifacts
      # https://github.com/actions/upload-artifact#too-many-uploads-resulting-in-429-responses
      run: tar czf exported-artifacts.tar.gz exported-artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: exported-artifacts.tar.gz
